spring.application.name=email-assistant
server.port=8085

spring.config.import=optional:file:.env[.properties]

gemini.api.key=${GEMINI_API_KEY:}
gemini.api.url=${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent}
